#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apache2',         '1.0.0'
cookbook 'apt',             '1.1.2'
cookbook 'build-essential', '1.0.0'
cookbook 'gpg',             '0.0.1'
cookbook 'java',            '1.1.0'
cookbook 'jenkins',         #0.6.0
    :path => 'cookbooks-sources'
cookbook 'leiningen',       '0.2.0'
cookbook 'pennyworth',      #0.2.1
    :path => 'cookbooks-sources'
cookbook 'postfix',         '0.8.4'
cookbook 'reprepro',        #0.3.0
    :path => 'cookbooks-sources'
cookbook 'runit',           '0.14.2'

# DRUPAL
cookbook 'drush',
  :git => 'git@github.com:patcon/chef-drush.git',
  :ref => 'refactor'
cookbook 'git'
cookbook 'php'
cookbook 'mysql'

# PERSONAL
cookbook 'vim'
